<?php
$sidebar = !empty($sidebar) ? $sidebar : [];
extract($sidebar);

// $sidebar_class = !empty($sidebar_class) ? $sidebar_class : "sidebar-dark";
// $sidebar_toggle = !empty($sidebar_toggle) ? $sidebar_toggle : "all";
$sidebar_active = !empty($sidebar_active) ? $sidebar_active : [0, 0];

?>
<nav class="sidebar sidebar-dark scroll-item" data-sidebar="menu" data-menu-toggle="only">
  <!-- <div class="sidebar-header">
    <span> Planeatec </span>
  </div> -->
  <span class="heading">Intranet</span>
  <ul class="sidenav">

    <li>
      <a class="menu <?php if ($sidebar_active[0] == 1) {echo 'active';}?>" href="#" role="button">
        <i class="fa fa-list"></i> Padrón
      </a>
      <ul class="menu-items">

        <li>
          <a class="<?php if ($sidebar_active[0] == 1 && $sidebar_active[1] == 1) {echo 'active';}?>"
            href="admin/padron/padron.php">
            <i class="icofont icofont-curved-right"></i> Personas
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 1 && $sidebar_active[1] == 2) {echo 'active';}?>"
            href="admin/tipo-vivienda/tipo-vivienda.php">
            <i class="icofont icofont-curved-right"></i> Tipos de Vivienda
          </a>
        </li>

      </ul>
    </li>

    <li>
      <a class="menu <?php if ($sidebar_active[0] == 2) {echo 'active';}?>" href="#" role="button">
        <i class="fas fa-street-view"></i>
        Ubigeos
      </a>
      <ul class="menu-items">
        <li>
          <a class="<?php if ($sidebar_active[0] == 2 && $sidebar_active[1] == 1) {echo 'active';}?>"
            href="admin/pais/pais.php">
            <i class="fa fa-list"></i>
            Paises
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 2 && $sidebar_active[1] == 2) {echo 'active';}?>"
            href="admin/region/region.php">
            <i class="fa fa-list"></i>
            Regiones
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 2 && $sidebar_active[1] == 3) {echo 'active';}?>"
            href="admin/departamentos/departamentos.php">
            <i class="far fa-building"></i>
            Departamentos
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 2 && $sidebar_active[1] == 4) {echo 'active';}?>"
            href="admin/provincias/provincias.php">
            <i class="far fa-building"></i>
            Provincias
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 2 && $sidebar_active[1] == 5) {echo 'active';}?>"
            href="admin/distritos/distritos.php">
            <i class="far fa-building"></i>
            Distritos
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 2 && $sidebar_active[1] == 6) {echo 'active';}?>"
            href="admin/caserios/caserios.php">
            <i class="far fa-building"></i>
            Caserios
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 2 && $sidebar_active[1] == 7) {echo 'active';}?>"
            href="admin/sectores/sectores.php">
            <i class="far fa-building"></i>
            Sectores
          </a>
        </li>

      </ul>
    </li>

    <li>
      <a class="menu <?php if ($sidebar_active[0] == 5) {echo 'active';}?>" href="#" role="button">
        <i class="fa fa-list"></i> Accesos
      </a>
      <ul class="menu-items">

        <li>
          <a class="<?php if ($sidebar_active[0] == 5 && $sidebar_active[1] == 1) {echo 'active';}?>"
            href="admin/user/user.php">
            <i class="icofont icofont-curved-right"></i> Usuarios
          </a>
        </li>

        <!--  <li>
          <a class="<?php if ($sidebar_active[0] == 5 && $sidebar_active[1] == 1) {echo 'active';}?>" href="admin/persona/persona.php">
            <i class="icofont icofont-curved-right"></i> Personas
          </a>
        </li> -->

      </ul>
    </li>

  </ul>
</nav>