<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<?php
// extraemos todas la variables
extract($setvar);

$titulo      = !empty($titulo ) ? $titulo : "Admin | Trebol" ;
$follow      = !empty($follow ) ? $follow : "follow" ;
$description = !empty($description ) ? $description : "Trebol Adminstrador" ;
$keywords    = !empty($keywords ) ? $keywords : "Trebol" ;

$path = !empty($path) ? $path : 'admin/';

?>

<title><?php echo $titulo; ?></title>
<link rel="icon" href="<?php echo $path;?>favicon.ico" sizes="32x32" />
<meta name="robots" content="<?php echo $follow; ?>" />

<meta name="description" content="<?php echo $description; ?>" />
<meta name="keywords" content="<?php echo $keywords; ?>" />
<meta name="robots" content="<?php echo $setvar['follow']; ?>" />
<base href="http://localhost/helpers/php-generate/public/" />

<!-- <base href="/" /> -->

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">

<link rel="stylesheet" href="<?php echo $path;?>css/app.admin.css">