<?php
$sidebar = !empty($sidebar) ? $sidebar : [];
extract($sidebar);

// $sidebar_class = !empty($sidebar_class) ? $sidebar_class : "sidebar-dark";
// $sidebar_toggle = !empty($sidebar_toggle) ? $sidebar_toggle : "all";
$sidebar_active = !empty($sidebar_active) ? $sidebar_active : [0, 0];

?>
<nav class="sidebar sidebar-dark scroll-item" data-sidebar="menu" data-menu-toggle="only">
  <!-- <div class="sidebar-header">
    <span> Planeatec </span>
  </div> -->
  <span class="heading">Intranet</span>
  <ul class="sidenav">

    <li>
      <a class="menu <?php if ($sidebar_active[0] == 1) {echo 'active';}?>" href="#" role="button">
        <i class="fa fa-list"></i> Productos
      </a>
      <ul class="menu-items">

        <li>
          <a class="<?php if ($sidebar_active[0] == 1 && $sidebar_active[1] == 1) {echo 'active';}?>"
            href="admin/producto/producto.php">
            <i class="icofont icofont-curved-right"></i> Productos
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 1 && $sidebar_active[1] == 2) {echo 'active';}?>"
            href="admin/categoria/categoria.php">
            <i class="icofont icofont-curved-right"></i> Categorias
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 1 && $sidebar_active[1] == 3) {echo 'active';}?>"
            href="admin/sub-categoria/sub-categoria.php">
            <i class="icofont icofont-curved-right"></i> Sub Categorias
          </a>
        </li>

        <li>
          <a class="<?php if ($sidebar_active[0] == 1 && $sidebar_active[1] == 4) {echo 'active';}?>"
            href="admin/etiqueta/etiqueta.php">
            <i class="icofont icofont-curved-right"></i> Etiquetas
          </a>
        </li>

      </ul>
    </li>


    <li>
      <a class="menu <?php if ($sidebar_active[0] == 5) {echo 'active';}?>" href="#" role="button">
        <i class="fa fa-list"></i> Accesos
      </a>
      <ul class="menu-items">

        <li>
          <a class="<?php if ($sidebar_active[0] == 5 && $sidebar_active[1] == 1) {echo 'active';}?>"
            href="admin/user/user.php">
            <i class="icofont icofont-curved-right"></i> Usuarios
          </a>
        </li>

        <!--  <li>
          <a class="<?php if ($sidebar_active[0] == 5 && $sidebar_active[1] == 1) {echo 'active';}?>" href="admin/persona/persona.php">
            <i class="icofont icofont-curved-right"></i> Personas
          </a>
        </li> -->

      </ul>
    </li>

  </ul>
</nav>