<!-- header -->
<header class="header">
  <div class="container mx-auto px-4">
    <div class="flex items-center"><a alt="Gob.pe" class="flex items-center" href="/">
        <figure class="w-12">
          <img alt="Solicitud de pase personal laboral"
            src="./img/escudo-peru.svg">
        </figure>
        <figure class="w-20 hidden ml-2 sm:inline"><img alt="Solicitud de pase personal laboral"
            src="/assets/logo_gobpe-f4fe7fa80288da76f89003a2cd7401f84cec39c0c1d2fcfd6d58b5379318ef71.svg">
          </figure>
      </a>
      <div class="border-l mx-3 border-white h-10"></div>
      <div class="text-white font-bold text-xl leading-tight">Registro Padron - Municipalidad de Callanca</div>
    </div>
  </div>
</header>
<!-- </header> -->